language: python

python:
  - "3.6"

install:
  - pip install --upgrade pip
  - pip install -e .

script:
  - echo "Building the project"
  - find . -name  "*.py" -exec pylint '{}' \;
  - echo "Continuing with Tests"
  - cd flaskerino
  - python tests/test_index.py -v
